### ISSUE TITLE
Can't choose option 2 by importing wallet

### ISSUE THREAD

**Issue by Escapeler** [DillLabs/launch-dill-node#23]
./dill.sh: line 70: /root/dill/2_add_validator.sh: No such file or directory

**Comment by PatrickSky131** [comment]
delete "add validator" in dill.sh.

Needs to run the script 2_add_validator.sh in dill directory now.
https://github.com/DillLabs/launch-dill-node?tab=readme-ov-file#add-a-validator-to-existing-node
